### PR TITLE
PlanRob

### PR DESCRIPTION
**Pull request by iawaad**
PlanRob page updated for 2024

### CODE REVIEW

**Comment by iawaad** [comment]
Hi Gloria, 

I just tried to update the PlanRob Workshop page but without much luck. I had updated the dates to the following: 

- Paper submission: ***Monday, 25 March 2024***
- Notification of acceptance: Friday, 26 April 2024
- Camera-ready version due: Friday 24 May 2024
- Workshop Date: June 2-3, 2024

to sync better with the rest of the workshops… but somehow, I’m getting the status that the working group is clean after I committed  but on github in the browser, I’m not seeing my change and so can’t lodge a pull request. 

Please advise (and so sorry for the extra work).

Many thanks, 

Iman

**Comment by zlatanajanovic** [comment]
Hi Iman,

Did you make a new fork?

BR,
Zlatan

**Comment by iawaad** [comment]
Hi Zlatan,Thanks for the quick reply. Nope - just the one I made a few days ago to set up the 2024 page. Should I make a new one again just for updating the page with new dates?Many thanks,ImanOn 7 Feb 2024, at 23:23, Zlatan Ajanovic ***@***.***> wrote:﻿
Hi Iman,



Did you make a new fork?



BR,

Zlatan

**Comment by zlatanajanovic** [comment]
Yes, we would need a new fork for each change, as previous one is merged.

**Comment by iawaad** [comment]
Thank you so much and sorry for that — done :)
Have a lovely day!

**Pull request merged**
